@BASE=http://localhost:8080

### Create env
POST {{BASE}}/environment
Content-Type: application/json

{
    "name" : "meu env",
    "tags" : ["hml", "staging"],
    "base_url" : "http://stg.viniciusamelio.com.br"
}

### Update env
PUT {{BASE}}/environment/2150353345729003520
Content-Type: application/json

{
    "name" : "Meu env editadinho",
    "tags" : ["dev", "mvp"],
    "description" : "Então pega essa descrição",
    "base_url" : "https://webhook.site/bae63b0a-0234-4cb1-8a06-d395c8871f0f"
}