@BASE=http://localhost:8080

### Create request
POST {{BASE}}/request
Content-Type: application/json

{
    "name" : "create foo ",
    "path" : "/foo",
    "method" : "POST",
    "called_at" : "2006-01-02T15:10:05Z",
    "environment_id": -545255424,
    "user_id" : "pretty-little-liars",
    "body" : "{'foo' : 'bar edited againnn'}"
}

### Get requests
GET {{BASE}}/request
Content-Type: application/json