@BASE=http://localhost:8080

### Create session
POST {{BASE}}/session
Content-Type: application/json

{
    "environment_id" : -545255424,
    "user_id" : "vini.jhonson",
    "tags" : ["homolog", "beta-tester", "cool-tag"]
}

### Replay Session
POST {{BASE}}/session/2146018584579538944/replay
Content-Type: application/json

### Get sessions
GET {{BASE}}/session
Content-Type: application/json
