// @generated by protoc-gen-es v2.2.3
// @generated from file schema/schema.proto (package schema, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file schema/schema.proto.
 */
export declare const file_schema_schema: GenFile;

/**
 * @generated from message schema.Session
 */
export declare type Session = Message<"schema.Session"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: int32 environment_id = 2;
   */
  environmentId: number;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: repeated string tags = 4;
   */
  tags: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message schema.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export declare const SessionSchema: GenMessage<Session>;

/**
 * @generated from message schema.EnvironmentSessions
 */
export declare type EnvironmentSessions = Message<"schema.EnvironmentSessions"> & {
  /**
   * @generated from field: repeated schema.Session sessions = 1;
   */
  sessions: Session[];
};

/**
 * Describes the message schema.EnvironmentSessions.
 * Use `create(EnvironmentSessionsSchema)` to create a new message.
 */
export declare const EnvironmentSessionsSchema: GenMessage<EnvironmentSessions>;

