// @generated by protoc-gen-es v2.2.3
// @generated from file schema/schema.proto (package schema, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file schema/schema.proto.
 */
export const file_schema_schema = /*@__PURE__*/
  fileDesc("ChNzY2hlbWEvc2NoZW1hLnByb3RvEgZzY2hlbWEiwAEKB1Nlc3Npb24SCgoCaWQYASABKAUSFgoOZW52aXJvbm1lbnRfaWQYAiABKAUSDwoHdXNlcl9pZBgDIAEoCRIMCgR0YWdzGAQgAygJEi4KCmNyZWF0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjMKCnVwZGF0ZWRfYXQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSACIAQFCDQoLX3VwZGF0ZWRfYXQiOAoTRW52aXJvbm1lbnRTZXNzaW9ucxIhCghzZXNzaW9ucxgBIAMoCzIPLnNjaGVtYS5TZXNzaW9uQgpaCC4vc2NoZW1hYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message schema.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema = /*@__PURE__*/
  messageDesc(file_schema_schema, 0);

/**
 * Describes the message schema.EnvironmentSessions.
 * Use `create(EnvironmentSessionsSchema)` to create a new message.
 */
export const EnvironmentSessionsSchema = /*@__PURE__*/
  messageDesc(file_schema_schema, 1);

