// @generated by protoc-gen-es v2.2.3
// @generated from file schema/schema.proto (package schema, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file schema/schema.proto.
 */
export declare const file_schema_schema: GenFile;

/**
 * @generated from message schema.Session
 */
export declare type Session = Message<"schema.Session"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: int32 environment_id = 2;
   */
  environmentId: number;

  /**
   * @generated from field: string user_id = 3;
   */
  userId: string;

  /**
   * @generated from field: repeated string tags = 4;
   */
  tags: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message schema.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export declare const SessionSchema: GenMessage<Session>;

/**
 * @generated from message schema.Request
 */
export declare type Request = Message<"schema.Request"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: int32 environment_id = 2;
   */
  environmentId: number;

  /**
   * @generated from field: optional int32 session_id = 3;
   */
  sessionId?: number;

  /**
   * @generated from field: string user_id = 4;
   */
  userId: string;

  /**
   * @generated from field: string method = 5;
   */
  method: string;

  /**
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * @generated from field: string path = 7;
   */
  path: string;

  /**
   * @generated from field: optional string headers = 8;
   */
  headers?: string;

  /**
   * @generated from field: optional string body = 9;
   */
  body?: string;

  /**
   * @generated from field: google.protobuf.Timestamp called_at = 10;
   */
  calledAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 11;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp updated_at = 12;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: optional schema.Session session = 13;
   */
  session?: Session;
};

/**
 * Describes the message schema.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export declare const RequestSchema: GenMessage<Request>;

/**
 * @generated from message schema.EnvironmentSessions
 */
export declare type EnvironmentSessions = Message<"schema.EnvironmentSessions"> & {
  /**
   * @generated from field: repeated schema.Session sessions = 1;
   */
  sessions: Session[];
};

/**
 * Describes the message schema.EnvironmentSessions.
 * Use `create(EnvironmentSessionsSchema)` to create a new message.
 */
export declare const EnvironmentSessionsSchema: GenMessage<EnvironmentSessions>;

/**
 * @generated from message schema.EnvironmentRequests
 */
export declare type EnvironmentRequests = Message<"schema.EnvironmentRequests"> & {
  /**
   * @generated from field: repeated schema.Request requests = 1;
   */
  requests: Request[];
};

/**
 * Describes the message schema.EnvironmentRequests.
 * Use `create(EnvironmentRequestsSchema)` to create a new message.
 */
export declare const EnvironmentRequestsSchema: GenMessage<EnvironmentRequests>;

/**
 * @generated from message schema.SessionRequests
 */
export declare type SessionRequests = Message<"schema.SessionRequests"> & {
  /**
   * @generated from field: schema.Session session = 1;
   */
  session?: Session;

  /**
   * @generated from field: repeated schema.Request requests = 2;
   */
  requests: Request[];
};

/**
 * Describes the message schema.SessionRequests.
 * Use `create(SessionRequestsSchema)` to create a new message.
 */
export declare const SessionRequestsSchema: GenMessage<SessionRequests>;

