//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Calls struct {
	ID            *string `sql:"primary_key"`
	SessionID     *string
	EnvironmentID *string
	Name          string
	Method        string
	Path          *string
	Body          *string
	QueryParams   *string
	UserID        *string
	CalledAt      time.Time
	CreatedAt     *time.Time
	UpdatedAt     time.Time
}
