//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Requests struct {
	ID            *string `sql:"primary_key"`
	EnvironmentID *string
	SessionID     *string
	Name          string
	UserID        string
	Method        string
	Path          string
	Body          *string
	Headers       *string
	CalledAt      time.Time
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
}
