//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Sessions struct {
	ID            *string `sql:"primary_key"`
	EnvironmentID *string
	UserID        *string
	Tags          *string
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
}
